apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-commerce-login
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: e-commerce-login
    spec:
      containers:
        - name: e-commerce-login-container
          image: pasinduj97/e-commerce-login:v1
          ports:
            - containerPort: 4070
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
